#!/bin/bash
docker run --rm -it \
	-v $PWD/src:/app/src \
	-v $PWD/testing:/app/testing \
	-v $PWD/package.json:/app/package.json \
	-v $PWD/../sv-mongo-graph-utils/src/:/app/node_modules/@simpleview/sv-mongo-graph-utils \
	--add-host=graphql.kube.simpleview.io:192.168.50.100 \
	sv-mongo-graph-utils:local /bin/sh